;;; aider-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from aider.el

(autoload 'aider-plain-read-string "aider" "\
Read a string from the user with PROMPT and optional INITIAL-INPUT.
This function can be customized or redefined by the user.

(fn PROMPT &optional INITIAL-INPUT)")
(defalias 'aider-read-string 'aider-plain-read-string)
 (autoload 'aider-transient-menu "aider" "Transient menu for Aider commands." t)
(autoload 'aider-run-aider "aider" "\
Create a comint-based buffer and run \"aider\" for interactive conversation.
With the universal argument, prompt to edit aider-args before running.

(fn &optional EDIT-ARGS)" t)
(autoload 'aider-switch-to-buffer "aider" "\
Switch to the Aider buffer.
When `aider--switch-to-buffer-other-frame' is non-nil, open in a new frame.
If the current buffer is already the Aider buffer, do nothing." t)
(autoload 'aider-clear "aider" "\
Send the command \"/clear\" to the Aider buffer." t)
(autoload 'aider-reset "aider" "\
Send the command \"/reset\" to the Aider buffer." t)
(autoload 'aider-exit "aider" "\
Send the command \"/exit\" to the Aider buffer." t)
(autoload 'aider-add-or-read-current-file "aider" "\
Send the command \"COMMAND-PREFIX <current buffer file full path>\" to the corresponding aider comint buffer.

(fn COMMAND-PREFIX)")
(autoload 'aider-add-current-file "aider" "\
Send the command \"/add <current buffer file full path>\" to the corresponding aider comint buffer." t)
(autoload 'aider-current-file-read-only "aider" "\
Send the command \"/read-only <current buffer file full path>\" to the corresponding aider comint buffer." t)
(autoload 'aider-add-files-in-current-window "aider" "\
Add files in all buffers in the current Emacs window to the Aider buffer." t)
(autoload 'aider-general-command "aider" "\
Prompt the user to input COMMAND and send it to the corresponding aider comint buffer." t)
(autoload 'aider-code-change "aider" "\
Prompt the user for a command and send it to the corresponding aider comint buffer prefixed with \"/code \"." t)
(autoload 'aider-ask-question "aider" "\
Prompt the user for a command and send it to the corresponding aider comint buffer prefixed with \"/ask \".
If a region is active, append the region text to the question.
If cursor is inside a function, include the function name as context." t)
(autoload 'aider-general-question "aider" "\
Prompt the user for a general question and send it to the corresponding aider comint buffer prefixed with \"/ask \"." t)
(autoload 'aider-help "aider" "\
Prompt the user for a command and send it to the corresponding aider comint buffer prefixed with \"/help \"." t)
(autoload 'aider-architect-discussion "aider" "\
Prompt the user for a command and send it to the corresponding aider comint buffer prefixed with \"/architect \"." t)
(autoload 'aider-debug-exception "aider" "\
Prompt the user for a command and send it to the corresponding aider comint buffer prefixed with \"/debug \",
replacing all newline characters except for the one at the end." t)
(autoload 'aider-go-ahead "aider" "\
Send the command \"go ahead\" to the corresponding aider comint buffer." t)
(autoload 'aider-magit-show-last-commit "aider" "\
Show the last commit message using Magit.
If Magit is not installed, report that it is required." t)
(autoload 'aider-undo-last-change "aider" "\
Undo the last change made by Aider." t)
(autoload 'aider-function-refactor "aider" "\
Get the function name under cursor and send refactor command to aider.
The command will be formatted as \"/architect\" followed by refactoring instructions
for the specified function." t)
(autoload 'aider-region-refactor "aider" "\
Get a command from the user and send it to the corresponding aider comint buffer based on the selected region.
The command will be formatted as \"/architect \" followed by the user command and the text from the selected region." t)
(autoload 'aider-function-or-region-refactor "aider" "\
Call aider-function-refactor when no region is selected, otherwise call aider-region-refactor." t)
(autoload 'aider-region-explain "aider" "\
Get a command from the user and send it to the corresponding aider comint buffer based on the selected region.
The command will be formatted as \"/ask \" followed by the text from the selected region." t)
(autoload 'aider-function-explain "aider" "\
Ask Aider to explain the function under the cursor.
Prompts user for specific questions about the function." t)
(autoload 'aider-function-or-region-explain "aider" "\
Call aider-function-explain when no region is selected, otherwise call aider-region-explain." t)
(autoload 'aider-explain-symbol-under-point "aider" "\
Ask Aider to explain symbol under point, given the code line as background info." t)
(autoload 'aider-batch-add-dired-marked-files "aider" "\
Add multiple Dired marked files to the Aider buffer with the \"/add\" command." t)
(autoload 'aider-add-same-type-files-under-dir "aider" "\
Add all files with same suffix as current file under current directory to Aider.
If there are more than 40 files, refuse to add and show warning message." t)
(autoload 'aider-write-unit-test "aider" "\
Generate unit test code for current buffer.
Do nothing if current buffer is not visiting a file.
If current buffer filename contains 'test':
  - If cursor is inside a test function, implement that test
  - Otherwise show message asking to place cursor inside a test function
Otherwise:
  - If cursor is on a function, generate unit test for that function
  - Otherwise generate unit tests for the entire file" t)
(autoload 'aider-fix-failing-test-under-cursor "aider" "\
Report the current test failure to aider and ask it to fix the code.
This function assumes the cursor is on or inside a test function." t)
(autoload 'aider-implement-todo "aider" "\
Implement TODO comments in current context.
If region is selected, implement that specific region.
If cursor is on a comment line, implement that specific comment.
If cursor is inside a function, implement TODOs for that function.
Otherwise implement TODOs for the entire current file." t)
(autoload 'aider-change-model "aider" "\
Interactively select and change AI model in current aider session." t)
(autoload 'aider-send-line-or-region "aider" "\
Send text to the Aider buffer.
If region is active, send the selected region line by line.
Otherwise, send the line under cursor." t)
(autoload 'aider-send-region-by-line "aider" "\
Get the text of the current selected region, split them into lines,
strip the newline character from each line,
for each non-empty line, send it to aider session.
If no region is selected, show a message." t)
(autoload 'aider-send-block-or-region "aider" "\
Send the current active region text or, if no region is active, send the current paragraph content to the aider session.
When sending paragraph content, preserve cursor position and deactivate mark afterwards." t)
(autoload 'aider-open-prompt-file "aider" "\
Open aider prompt file under git repo root.
If file doesn't exist, create it with command binding help and sample prompt." t)
(autoload 'aider-minor-mode "aider" "\
Minor mode for Aider with keybindings.

This is a minor mode.  If called interactively, toggle the `Aider
minor mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `aider-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "aider" '("aider-"))


;;; Generated autoloads from aider-doom.el

(register-definition-prefixes "aider-doom" '("aider-doom-setup-keys"))


;;; Generated autoloads from aider-etc.el

(autoload 'aider-repo-find-name-dired "aider-etc" "\
Run `find-name-dired` from the Git repository root directory with the given PATTERN.

(fn PATTERN)" t)
(autoload 'aider-git-repo-root-dired "aider-etc" "\
Open a Dired buffer at the root of the current Git repository." t)


;;; Generated autoloads from aider-helm.el

(with-eval-after-load 'aider (if (featurep 'helm) (defalias 'aider-read-string 'aider-helm-read-string) (message "Helm is not available. Please install helm package to use aider-helm features")))
(register-definition-prefixes "aider-helm" '("aider-helm-read-string"))


;;; Generated autoloads from test_aider.el

(register-definition-prefixes "test_aider" '("face-differs-from-default-p"))

;;; End of scraped data

(provide 'aider-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; aider-autoloads.el ends here
