;;; aidermacs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from aidermacs.el

(autoload 'aidermacs-plain-read-string "aidermacs" "\
Read a string from the user with PROMPT and optional INITIAL-INPUT.
This function can be customized or redefined by the user.

(fn PROMPT &optional INITIAL-INPUT)")
(defalias 'aidermacs-read-string 'aidermacs-plain-read-string)
 (autoload 'aidermacs-transient-menu "aidermacs" "Transient menu for aidermacs commands." t)
(autoload 'aidermacs-run-aidermacs "aidermacs" "\
Run aidermacs process using the selected backend.
With the universal argument, prompt to edit aidermacs-args before running.

(fn &optional EDIT-ARGS)" t)
(autoload 'aidermacs-switch-to-buffer "aidermacs" "\
Switch to the aidermacs buffer.
When `aidermacs--switch-to-buffer-other-frame' is non-nil, open in a new frame.
If the current buffer is already the aidermacs buffer, do nothing." t)
(autoload 'aidermacs-clear "aidermacs" "\
Send the command \"/clear\" to the aidermacs buffer." t)
(autoload 'aidermacs-reset "aidermacs" "\
Send the command \"/reset\" to the aidermacs buffer." t)
(autoload 'aidermacs-exit "aidermacs" "\
Send the command \"/exit\" to the aidermacs buffer." t)
(autoload 'aidermacs-add-or-read-current-file "aidermacs" "\
Send the command \"COMMAND-PREFIX <current buffer file full path>\" to the corresponding aidermacs comint buffer.

(fn COMMAND-PREFIX)")
(autoload 'aidermacs-add-current-file "aidermacs" "\
Send the command \"/add <current buffer file full path>\" to the corresponding aidermacs comint buffer." t)
(autoload 'aidermacs-current-file-read-only "aidermacs" "\
Send the command \"/read-only <current buffer file full path>\" to the corresponding aidermacs comint buffer." t)
(autoload 'aidermacs-add-files-in-current-window "aidermacs" "\
Add files in all buffers in the current Emacs window to the aidermacs buffer." t)
(autoload 'aidermacs-general-command "aidermacs" "\
Prompt the user to input COMMAND and send it to the corresponding aidermacs comint buffer." t)
(autoload 'aidermacs-code-change "aidermacs" "\
Prompt the user for a command and send it to the corresponding aidermacs comint buffer prefixed with \"/code \"." t)
(autoload 'aidermacs-ask-question "aidermacs" "\
Prompt the user for a command and send it to the corresponding aidermacs comint buffer prefixed with \"/ask \".
If a region is active, append the region text to the question.
If cursor is inside a function, include the function name as context." t)
(autoload 'aidermacs-general-question "aidermacs" "\
Prompt the user for a general question and send it to the corresponding aidermacs comint buffer prefixed with \"/ask \"." t)
(autoload 'aidermacs-help "aidermacs" "\
Prompt the user for a command and send it to the corresponding aidermacs comint buffer prefixed with \"/help \"." t)
(autoload 'aidermacs-architect-discussion "aidermacs" "\
Prompt the user for a command and send it to the corresponding aidermacs comint buffer prefixed with \"/architect \"." t)
(autoload 'aidermacs-debug-exception "aidermacs" "\
Prompt the user for a command and send it to the corresponding aidermacs comint buffer prefixed with \"/debug \",
replacing all newline characters except for the one at the end." t)
(autoload 'aidermacs-go-ahead "aidermacs" "\
Send the command \"go ahead\" to the corresponding aidermacs comint buffer." t)
(autoload 'aidermacs-magit-show-last-commit "aidermacs" "\
Show the last commit message using Magit.
If Magit is not installed, report that it is required." t)
(autoload 'aidermacs-undo-last-change "aidermacs" "\
Undo the last change made by aidermacs." t)
(autoload 'aidermacs-function-or-region-refactor "aidermacs" "\
Refactor code at point or region.
If region is active, refactor that region.
If point is in a function, refactor that function." t)
(autoload 'aidermacs-region-explain "aidermacs" "\
Get a command from the user and send it to the corresponding aidermacs comint buffer based on the selected region.
The command will be formatted as \"/ask \" followed by the text from the selected region." t)
(autoload 'aidermacs-function-explain "aidermacs" "\
Ask aidermacs to explain the function under the cursor.
Prompts user for specific questions about the function." t)
(autoload 'aidermacs-function-or-region-explain "aidermacs" "\
Call aidermacs-function-explain when no region is selected, otherwise call aidermacs-region-explain." t)
(autoload 'aidermacs-explain-symbol-under-point "aidermacs" "\
Ask aidermacs to explain symbol under point, given the code line as background info." t)
(autoload 'aidermacs-batch-add-dired-marked-files "aidermacs" "\
Add multiple Dired marked files to the aidermacs buffer with the \"/add\" command." t)
(autoload 'aidermacs-add-same-type-files-under-dir "aidermacs" "\
Add all files with same suffix as current file under current directory to aidermacs.
If there are more than 40 files, refuse to add and show warning message." t)
(autoload 'aidermacs-write-unit-test "aidermacs" "\
Generate unit test code for current buffer.
Do nothing if current buffer is not visiting a file.
If current buffer filename contains 'test':
  - If cursor is inside a test function, implement that test
  - Otherwise show message asking to place cursor inside a test function
Otherwise:
  - If cursor is on a function, generate unit test for that function
  - Otherwise generate unit tests for the entire file" t)
(autoload 'aidermacs-fix-failing-test-under-cursor "aidermacs" "\
Report the current test failure to aidermacs and ask it to fix the code.
This function assumes the cursor is on or inside a test function." t)
(autoload 'aidermacs-implement-todo "aidermacs" "\
Implement TODO comments in current context.
If region is selected, implement that specific region.
If cursor is on a comment line, implement that specific comment.
If cursor is inside a function, implement TODOs for that function.
Otherwise implement TODOs for the entire current file." t)
(autoload 'aidermacs-send-line-or-region "aidermacs" "\
Send text to the aidermacs buffer.
If region is active, send the selected region line by line.
Otherwise, send the line under cursor." t)
(autoload 'aidermacs-send-region-by-line "aidermacs" "\
Get the text of the current selected region, split them into lines,
strip the newline character from each line,
for each non-empty line, send it to aidermacs session.
If no region is selected, show a message." t)
(autoload 'aidermacs-send-block-or-region "aidermacs" "\
Send the current active region text or, if no region is active, send the current paragraph content to the aidermacs session.
When sending paragraph content, preserve cursor position and deactivate mark afterwards." t)
(autoload 'aidermacs-open-prompt-file "aidermacs" "\
Open aidermacs prompt file under git repo root.
If file doesn't exist, create it with command binding help and sample prompt." t)
(autoload 'aidermacs-minor-mode "aidermacs" "\
Minor mode for aidermacs with keybindings.

This is a minor mode.  If called interactively, toggle the
`aidermacs minor mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `aidermacs-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "aidermacs" '("aidermacs-"))


;;; Generated autoloads from aidermacs-backend-comint.el

(register-definition-prefixes "aidermacs-backend-comint" '("aidermacs-"))


;;; Generated autoloads from aidermacs-backend-vterm.el

(register-definition-prefixes "aidermacs-backend-vterm" '("aidermacs-"))


;;; Generated autoloads from aidermacs-backends.el

(register-definition-prefixes "aidermacs-backends" '("aidermacs-"))


;;; Generated autoloads from aidermacs-doom.el

(register-definition-prefixes "aidermacs-doom" '("aidermacs-doom-setup-keys"))


;;; Generated autoloads from aidermacs-helm.el

(with-eval-after-load 'aidermacs (if (featurep 'helm) (defalias 'aidermacs-read-string 'aidermacs-helm-read-string) (message "Helm is not available. Please install helm package to use aidermacs-helm features")))
(register-definition-prefixes "aidermacs-helm" '("aidermacs-helm-read-string"))


;;; Generated autoloads from aidermacs-models.el

(autoload 'aidermacs-change-model "aidermacs-models" "\
Interactively select and change AI model in current aidermacs session." t)
(register-definition-prefixes "aidermacs-models" '("aidermacs-"))


;;; Generated autoloads from aidermacs-utils.el

(autoload 'aidermacs-repo-find-name-dired "aidermacs-utils" "\
Run `find-name-dired` from the Git repository root directory with the given PATTERN.

(fn PATTERN)" t)
(autoload 'aidermacs-git-repo-root-dired "aidermacs-utils" "\
Open a Dired buffer at the root of the current Git repository." t)

;;; End of scraped data

(provide 'aidermacs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; aidermacs-autoloads.el ends here
